spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.202.115:3306/forjdbc?characterEncoding=utf8
    url: jdbc:mysql://192.168.201.126:3306/forjdbc?characterEncoding=utf8
    username: root
    password: houzhiming
    dbcp2:
      initial-size: 1
    tomcat:
      max-wait: 60000
      max-active: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
  #    host: 192.168.1.111
  #    host: 192.168.202.111
      host: 47.101.152.55
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: 1s
          max-idle: 8
          min-idle: 0
      timeout: 1s
server:
  port: 8080
logging:
  level:
    houzm.accumulation.cache: debug
#redis config
